- hosts: k8s-cluster
  gather_facts: no
  become: yes
  tasks:
    - name: update packages
      yum: 
        name: '{{item}}'
        state: latest
      with_items:
        - kubectl
        - kubeadm
        - kubelet
        - kubernetes-cni

    - name: restart kubelet service
      service: name=kubelet state=restarted enabled=yes

- hosts: k8s-master
  gather_facts: no
  become: yes
  tasks:
    - name: remove kube-proxy
      shell: KUBECONFIG=/etc/kubernetes/admin.conf kubectl delete daemonset kube-proxy -n kube-system
      ignore_errors: yes

    - name: upgrade kubeadm
      shell: kubeadm init --skip-preflight-checks --kubernetes-version v1.7.1