- name: install keepalived
  become: yes
  yum:
    name: keepalived
  notify:
    - restart keepalived service

- name: deploy keepalived script
  become: yes
  copy:
    src: check_apiserver.sh
    dest: /etc/keepalived/check_apiserver.sh
    mode: "a+x"

- name: deploy keepalived config
  become: yes
  template:
    src: keepalived.conf
    dest: /etc/keepalived/keepalived.conf
  notify:
    - restart keepalived service
